jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/')
      name: Set release tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - continue-on-error: true
      env:
        BUILD_ID: ${{ github.run_number }}
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      name: Upload prod artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: 'build/libs/

          !build/libs/*-sources.jar

          '
    - continue-on-error: true
      name: Upload dev artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/devlibs/
name: gradle-ci
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
