jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/')
      name: Set release tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - continue-on-error: true
      if: github.event.release.prerelease
      name: Set build id
      run: echo "BUILD_ID=SNAPSHOT" >> $GITHUB_ENV
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      name: Upload assets to GitHub
      uses: AButler/upload-release-assets@v2.0
      with:
        files: build/libs/*;!build/libs/*-sources.jar;build/devlibs/*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: release-artifacts
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
